# epochs: Number of epochs
# batch_size: Batch size to be used for training
# lr: Learning rate for the optimizer (Adam)
# num_samples: Total samples to be used for training from the data directory
# height: Height of the input (do not change this)
# width: Width of the input (do not change this)
# data: Path to the directory with tf record files in the same directory structure as in datasets/256/tfrecords
# ckpt_dir: Path to the directory where the checkpoints are stored
# summary_dir: Path to the directory where the summaries are stored
# model_ckpt: Path to any previous checkpoint to be loaded before training (optional)

{
  'epochs': 200,
  'batch_size': 16,
  'lr': 3e-4,
  'num_samples': 4000,
  'height': 256,
  'width': 256,
  'data': './datasets/256/tfrecords',
  'ckpt_dir': './checkpoints',
  'summary_dir': './summaries',
  'model_ckpt': ''
}
