# epochs: Number of epochs
# batch_size: Batch size to be used for training
# lr: Learning rate for the optimizer (Adam)
# num_samples: Total samples to be used for training from the data directory
# height: Height of the input (do not change this)
# width: Width of the input (do not change this)
# data: Path to the directory with tf record files in the same directory structure as in datasets/256/tfrecords
# ckpt_dir: Path to the directory where the checkpoints are stored
# summary_dir: Path to the directory where the summaries are stored
# model_ckpt: Path to any previous checkpoint to be loaded before training (optional)

data:
  height: 256
  width: 256
  data_dir: 'datasets/energy/tfrecords'

model:
  input_dim: 3
  output_dim: 17

train:
  augment: False
  shuffle: True
  num_samples: 100
  batch_size: 16
  epochs: 100
  run_test: False
  log:
    sum_step: 5
  optim:
    type: adam
    lr: 0.0003
    beta1: 0.9
  out_dir: 'out/'
  ckpt_path: ''
