{
  'height': 128,
  'width': 128,
  'num_samples': 10,
  'latent_dimensions': 64,
  'data': './datasets/128/tfrecords',
  'gen_ckpt': '/home/harinandan/TUM/sose2019/IDP/building-design-assistant/checkpoints/20200108/110459/gen_20200108_165554_9.h5'
}

