data:
  height: 256
  width: 256
  data_dir: 'datasets/energy/tfrecords'

model:
  input_dim: 1
  output_dim: [3, 10]
  lat_dim: 32
  meta_dim: 14


test:
  num_samples: 30
  #'latent_dimensions': 64
  #'meta_dimensions': 12
  gen_ckpt: 'out/20200810/205338/checkpoints/20200814_041804_195.h5'
  corner_ckpt: 'out/20200814/095456/checkpoints/20200814_105412_195.h5'