data:
  height: 256
  width: 256
  data_dir: 'datasets/energy/tfrecords'

model:
  input_dim: 1
  output_dim: [3, 10]
  lat_dim: 32
  meta_dim: 14


test:
  num_samples: 30
  type: one_to_many
  num_outputs: 20 # Number of outputs for each shape when one to many is used
  iterations: 1000 # Number of iterations to be used to reconstruct input data.
  gen_ckpt: 'out/gen_20200820_071350_160.h5'
  corner_ckpt: 'out/corner_20200814_105412_195.h5'