{
  'epochs': 100,
  'batch_size': 32,
  'gen_lr': 1e-4,
  'lat_lr': 6e-2,
  'latent_iterations': 50,
  'generator_iterations': 2,
  'num_samples': 4500,
  'height': 256,
  'width': 256,
  'latent_dimensions': 64,
  'data': '/home/ubuntu/datasets/tfrecords',
  'ckpt_dir': '/home/ubuntu/checkpoints',
  'summary_dir': '/home/ubuntu/summaries',
  'gen_ckpt': '/home/ubuntu/checkpoints/gen_20200118_093041_0.h5'
}
