{
  'epochs': 40,
  'batch_size': 32,
  'gen_lr': 5e-4,
  'lat_lr': 3e-2,
  'latent_iterations': 50,
  'generator_iterations': 2,
  'num_samples': 5100,
  'height': 256,
  'width': 256,
  'latent_dimensions': 64,
  'data': './datasets/256/tfrecords',
  'ckpt_dir': './checkpoints',
  'summary_dir': './summaries',
  'gen_ckpt': ''
}
