data:
  height: 256
  width: 256
  data_dir: '/home/ubuntu/datasets/tfrecords'

model:
  input_dim: 1
  output_dim: [3, 10]
  lat_dim: 32
  meta_dim: 14

train:
  augment: True
  max_trans_x: 10
  max_trans_y: 10
  shuffle: True
  num_samples: 4000
  batch_size: 32
  epochs: 200
  run_test: False
  log:
    sum_step: 5
  lat:
    iter: 50
    optim:
      type: adam
      lr: 0.06
      beta1: 0.9
    dim: 32
  gen:
    iter: 2
    optim:
      type: adam
      lr: 0.0004
      beta1: 0.9
  out_dir: '/home/ubuntu/out/'
  ckpt_path: ''