{
  'epochs': 40,
  'batch_size': 32,
  'gen_lr': 2e-4,
  'lat_lr': 3e-2,
  'latent_iterations': 50,
  'generator_iterations': 2,
  'num_samples': 5000,
  'height': 128,
  'width': 128,
  'latent_dimensions': 64,
  'data': './datasets/128/filtered/tfrecords',
  'ckpt_dir': './checkpoints',
  'summary_dir': './summaries',
  'gen_ckpt': '/home/harinandan/TUM/sose2019/IDP/building-design-assistant/checkpoints/20200108/002746/gen_20200108_081500_13.h5'
}
