# epochs: Number of epochs
# batch_size: Batch size to be used for training
# gen_lr: Learning rate for the optimizer used to train the generator (Adam)
# lat_lr: Learning rate for the optimizer used to train the latent codes (Adam)
# latent_iterations: Number of optimization steps for latent codes
# generator_iterations: Number of optimization steps for generator
# num_samples: Total samples to be used for training from the data directory
# height: Height of the input (do not change this)
# width: Width of the input (do not change this)
# latent_dimensions: Number of dimensions of the latent code
# meta_data_dimensions: Number of other values such as room types indicator, cooling, heating parameters etc.
# data: Path to the directory with tf record files in the same directory structure as in datasets/256/tfrecords
# ckpt_dir: Path to the directory where the checkpoints are stored
# summary_dir: Path to the directory where the summaries are stored
# gen_ckpt: Path to any previous checkpoint to be loaded before training (optional)

data:
  height: 256
  width: 256
  data_dir: 'datasets/energy/tfrecords'

model:
  input_dim: 1
  output_dim: [3, 10]
  lat_dim: 32
  meta_dim: 14

train:
  augment: True
  trans:
    status: False
    max_x: 1
    max_y: 1
  rotate: True
  shuffle: True
  num_samples: 4000
  batch_size: 16
  epochs: 30
  run_test: False
  log:
    sum_step: 5
  lat:
    iter: 100
    optim:
      type: adam
      lr: 0.06
      beta1: 0.9
    dim: 32
  gen:
    iter: 5
    optim:
      type: adam
      lr: 0.0004
      beta1: 0.9
  out_dir: 'out/'
  ckpt_path: ''
