{
  'epochs': 200,
  'batch_size': 32,
  'gen_lr': 3e-4,
  'disc_lr': 1e-4,
  'loss_coeff': 50,
  'num_samples': 7000,
  'height': 128,
  'width': 128,
  'latent_dimensions': 4,
  'data': './datasets/128/tfrecords',
  'ckpt_dir': './checkpoints',
  'summary_dir': './summaries',
  'gen_ckpt': '',
  'disc_ckpt': '',
}
