# input_dir: Path to the directory where the vector files are stored
# output_dir: Path to the directory where the output files are to be stored.
#             The directory is created if it doesnt exist
# output_type: tfrecord or hdf5 or png. Type of the output you want to generate.
#              tfrecords have only the masks of the floor plan
#              hdf5 have masks and segmentation images
#              png outputs only segmentation images
# width: Width of the output
# height: Height of the output
# num_output_images: Maximum number of images to be transformed and stored

dir:
  input: '../public_datasets/filtering_v3/energy_vectors'
  output: 'datasets/energy/tfrecords'
out:
  type: 'tfrecord'
  width: 256
  height: 256
  num_samples: 5500
thickness:
  wall: 3
  window: 3
  door: 3
  corner: 3
shuffle: True
