# input_dir: Path to the directory where the vector files are stored
# output_dir: Path to the directory where the output files are to be stored.
#             The directory is created if it doesnt exist
# output_type: tfrecord or hdf5 or png. Type of the output you want to generate.
#              tfrecords have only the masks of the floor plan
#              hdf5 have masks and segmentation images
#              png outputs only segmentation images
# width: Width of the output
# height: Height of the output
# num_output_images: Maximum number of images to be transformed and stored

{
  'input_dir': '../public_datasets/cleanedup_vectors',
  'output_dir': './datasets/256/tfrecords/train',
  'output_type': 'tfrecord' ,
  'width': 256,
  'height': 256,
  'num_output_images': -1,
  'wall_thickness': 3,
  'window_thickness': 3,
  'door_thickness': 3,
  'corner_thickness': 3,
  'shuffle': 'True'
}
